export const title = 'After School Learning';
export const alphabetVideoList: any = {
  a: 'https://www.youtube.com/watch?v=hBAuIzZttP4',
  b: 'https://www.youtube.com/watch?v=W5D3ySh7s2c',
  c: 'https://www.youtube.com/watch?v=ieo0LPYdUfQ',
  d: 'https://www.youtube.com/watch?v=NqntSJGu1t0',
  e: 'https://www.youtube.com/watch?v=Cm4OnFLl5Uw',
  f: 'https://www.youtube.com/watch?v=oT5Rzwj1xdw',
  g: 'https://www.youtube.com/watch?v=ru0KCAS5zuY',
  h: 'https://www.youtube.com/watch?v=C8EtaVKk8Fg',
  i: 'https://www.youtube.com/watch?v=tGxaEdXOSk8',
  j: 'https://www.youtube.com/watch?v=TeYynmQ0v3Q',
  k: 'https://www.youtube.com/watch?v=j_LNrXd7Jx8',
  l: 'https://www.youtube.com/watch?v=T4YvWb0WMRQ',
  m: 'https://www.youtube.com/watch?v=YiK7IL0kqd0',
  n: 'https://www.youtube.com/watch?v=hCxv2ZPU3vg',
  o: 'https://www.youtube.com/watch?v=-EgEt0aru90',
  p: 'https://www.youtube.com/watch?v=HMMy6Y-nduE',
  q: 'https://www.youtube.com/watch?v=US7-1k5oHdE',
  r: 'https://www.youtube.com/watch?v=-9BzWBufH1s',
  s: 'https://www.youtube.com/watch?v=1orYZAoGgoQ',
  t: 'https://www.youtube.com/watch?v=M5gUg06rock',
  u: 'https://www.youtube.com/watch?v=yWiRgOuaS84',
  v: 'https://www.youtube.com/watch?v=A1BeBFqwyFc',
  w: 'https://www.youtube.com/watch?v=4yCg2dZaaD0',
  x: 'https://www.youtube.com/watch?v=qj4nyH2aWVc',
  y: 'https://www.youtube.com/watch?v=TWJSE_p0akY',
  z: 'https://www.youtube.com/watch?v=wLu-bccANRg',
};

export const sketchColors = {
  pink: '#ff598f',
  yellow: '#ffff01',
  lightGreen: '#68fa9f',
  purple: '#6c23e6',
  blue: '#0d9cf4',
  orange: '#ff9900',
  black: '#282a2d',
  red: '#f81c00',
  grey: '#d5d8dd',
};
